new models and mockData
iOS-vk-education/2023_1_iSnoops pull request #10
Opened 2023-12-04 10:00 UTC by gp8stvlv

2023-12-05 13:28 UTC, blackplayerten requested changes

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/WordApiModel.swift
> +    let linkedWordsId: String // Связующий идентификатор для связи с категорией
изменить на categoryID

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/Errors/ImageManagerErrors.swift
> +    case unexpectedError
можно еще добавить failedImageData, wrongLink

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/Errors/NetworkErrors.swift
> +    case idError
какой id?

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/Errors/NetworkErrors.swift
> +    case urlError
unexpectedURL

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/Errors/NetworkErrors.swift
> +    case unexpectedError
слово error в конце нейминга бессмысленное

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/MockData.swift
> +// swiftlint:disable all
интересно ошибки линтера исправляем, нельзя так

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/MockData.swift
> +                         createdDate: Date().addingTimeInterval(-6),
можно просто currentDate устанавливать

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/Models/WordModel.swift
> +struct WordModel {
тут date не нужна, можно сразу в api проставлять текущую дату
words поле я не поняла что обозначает
12 строка categoryID тогда (но зачем тут это поле, если оно будет присылаться с бека, на ui не менятся (или будет?), можно тоже самое отправлять обратно)

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/WordApiModel.swift
> +    let words: [String: String]
words поле я не поняла что обозначает

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
> +    let createdDate: Date
убрать, раз не используется на ui

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
>      let title: [String: String]
почему название категории словарем?

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
> +    let linkedWordsId: String // Связующий идентификатор для слов в категории
не уверена, что он тут нужен, подумать над этим
если у вас добавление слов возможно только в пределах одной категории, то для ui этот идентификатор не несет никакой ценности, а нужен условно только для бека, чтобы знать в какую категорию его записать

2023-12-05 13:28 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/CategoryApiModel.swift
>      let imageLink: String?
почему опционал? у вас разве не или картинка выбранная пользователем, или дефолтная?

2023-12-05 14:45 UTC, gp8stvlv commented on easyLanguage/Network/MockData.swift
> +                         createdDate: Date().addingTimeInterval(-6),
для проверки сортировки изменял

2023-12-05 19:01 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
>      let title: [String: String]
на разных языках

2023-12-05 19:02 UTC, gp8stvlv commented on easyLanguage/Network/ApiModels/WordApiModel.swift
> +    let linkedWordsId: String // Связующий идентификатор для связи с категорией
так это же не совсем id, id у категории это первычный ключ, а не идентификатор связи

2023-12-05 19:06 UTC, gp8stvlv commented on easyLanguage/Network/ApiModels/CategoryApiModel.swift
>      let imageLink: String?
если она не установлена, то что хранить? Дефолтная на фронте будет добавляться уже

2023-12-06 14:46 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
> +    let createdDate: Date
на экране который Саша должен делать, можно сделать сортировку на дате

2023-12-06 14:46 UTC, gp8stvlv commented on easyLanguage/Network/ApiModels/WordApiModel.swift
> +    let words: [String: String]
слово на нескольких языках

2023-12-06 14:46 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
>      let title: [String: String]
тоже думал на нескольких языках , но да, бессмысленно

2023-12-06 14:47 UTC, gp8stvlv commented on easyLanguage/Network/Errors/ImageManagerErrors.swift
> +    case unexpectedError
✅

2023-12-06 14:47 UTC, gp8stvlv commented on easyLanguage/Network/Errors/NetworkErrors.swift
> +    case idError
✅

2023-12-06 14:47 UTC, gp8stvlv commented on easyLanguage/Network/Errors/NetworkErrors.swift
> +    case urlError
✅

2023-12-06 14:47 UTC, gp8stvlv commented on easyLanguage/Network/Errors/NetworkErrors.swift
> +    case unexpectedError
✅

2023-12-06 14:47 UTC, gp8stvlv commented on easyLanguage/Network/MockData.swift
> +// swiftlint:disable all
можно все-таки не исправлять мок дату?)))

2023-12-06 14:53 UTC, gp8stvlv commented on easyLanguage/Network/Models/WordModel.swift
> +struct WordModel {
date  - на экране, который Саша должен делать, можно сделать сортировку на дате
words - слово на нескольких языках, можно переименовать по типу wordTranslations
categoryID(linkedWordsId) - нужен, чтобы загрузить нужный экран

2023-12-06 14:54 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
> +    let createdDate: Date
✅

2023-12-06 14:55 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
> +    let linkedWordsId: String // Связующий идентификатор для слов в категории
скорее всего не нужен, да

2023-12-07 13:55 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/WordApiModel.swift
> +    let linkedWordsId: String // Связующий идентификатор для связи с категорией
ты путаешь бд и модельки айосные) 
у тебя модель одного слова и в нем связь с другими словами, логическая ошибка
у вас слова связаны только по категориям

2023-12-07 13:57 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/WordApiModel.swift
> +    let words: [String: String]
тогда это переводы, translations

2023-12-07 13:59 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/CategoryApiModel.swift
>      let imageLink: String?
так, а тут у тебя не фронт?) ты в эту модель парсишь то, что приходит с сети. можешь распарсить сразу в данные с картинки ассета, например

2023-12-07 16:01 UTC, blackplayerten requested changes

2023-12-07 16:01 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/WordApiModel.swift
> +    let createdDate: Date
сомнительно, но окей

2023-12-07 16:01 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/WordApiModel.swift
> +    let wordId: Int // PK
убрать

2023-12-09 08:25 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Categories/CategoryUIModel.swift
>  final class CategoryUIModel {
структура

2023-12-09 08:25 UTC, blackplayerten commented on easyLanguage/Network/Models/WordModel.swift
> +    let linkedCategoryId: String // Связующий идентификатор для связи с категорией
linked можно убрать

2023-12-09 11:58 UTC, blackplayerten approved these changes

2023-12-09 11:58 UTC, merged