added VC CategoryDetail
iOS-vk-education/2023_1_iSnoops pull request #21
Opened 2023-12-10 18:13 UTC by gp8stvlv

2023-12-24 16:52 UTC, blackplayerten requested changes

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/Application/SceneDelegate.swift
> +        window?.rootViewController = CategoryDetailViewController()
не забыть вернуть таббар

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +    private var wordsModel: [WordUIModel] = []
можно private var wordsModel = [WordUIModel]()

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +        setNavBar()
вызовы местами поменять, логичнее будет)

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +    private var numberOfSelectedCategory = 2 //FIXME: - будут данные из ячейки catalogVC
selectedCategory: Int

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +    private var wordsModel: [WordUIModel] = []
поменять местами

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +    private var numberOfSelectedCategory = 2 //FIXME: - будут данные из ячейки catalogVC
поместить ниже после поля model

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +    func configureCategoryDetailViewController(linkedWordsId: String) {
не configure, а set(linkedWordsID: String)

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +    func buttonTapped() {
addNewWordButtonTapped()

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Services/CategoryDetailNetworkManager.swift
> +    func postWord(with newWord: WordApiModel, completion: @escaping (Result<Void, Error>) -> Void)
addWord

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Services/CategoryDetailNetworkManager.swift
> +    private init() {}
не нужно

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +        }
в addConstraints

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +    private let markIcon = UIImageView()
непонятно что за марк, тогда уж markAsLearned

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +    private var cellBackgroundColor: UIColor?
лучше поместить на 16 строку, backgroundColor

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +        updateLike(with: wordUIModel.isLearned)
updateMark(isLearned: wordUIModel.isLearned)

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +        if isFlipped {
isFlipped ? (title.text = foreignTitle) : (title.text = nativeTitle)

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +    func didTapCell() {
showTranslation

2023-12-24 16:52 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +        // обновление лайка на беке
отсюда мы запросы на бек не делаем

2023-12-25 09:21 UTC, gp8stvlv commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +        // обновление лайка на беке
отсюда и не будет, это TODO скорее)

2023-12-26 10:47 UTC, blackplayerten approved these changes

2023-12-26 10:48 UTC, blackplayerten approved these changes

2023-12-26 10:48 UTC, merged