Structure project grigoriy
iOS-vk-education/2023_1_iSnoops pull request #3
Opened 2023-10-26 11:38 UTC by gp8stvlv

2023-10-26 12:20 UTC, blackplayerten commented on README.md
> +  <li>Пустовалов Григорий (Тимлид) - пишет бэк <a href="https://github.com/gp8stvlv">Git</a></li>
- [x] Лучше в формат маркдауна переделать. 

В vscode, например, есть редактирование маркдауна сразу с просмотром.
У вас указан Git (что неправильно), потому что гит – это система контроля версий, а гитхаб – пространство с вашими кодингами (условно).
- [x] Нужно будет в слова "Пустовалов Григорий" добавить ссылку на гитхаб профиль

- [x] тоже самое с остальными ребятами
- [x] '+' в описание о себе написать распределение обязанностей по экранам

2023-10-26 12:20 UTC, blackplayerten commented on README.md
> +  <li>Верстка - Кодом</li>
- [ ] Верстка – autolayout (code)

потому что можно кодом и на фреймах верстать

2023-10-26 12:20 UTC, blackplayerten commented on README.md
> +  <li>Библиотека - third party</li>
- [ ] не библиотека – ..., а: обучение слов в виде карточек тиндера – third party library

'+' добавить (необязательно): 
организация работы в notion (kanban board) 
общение через zoom-созвоны

2023-10-26 12:20 UTC, blackplayerten commented on easyLanguage/Application/AppDelegate.swift
> +
- [ ] убрать лишние пустые строки
- [ ] добавить swiftlint в проект

2023-10-26 12:20 UTC, blackplayerten commented on easyLanguage/Application/AppDelegate.swift
> +        // Override point for customization after application launch.
(опционально) сюда добавить запуск приложения, чтобы с более ранних версий ios поддерживать

2023-10-26 12:20 UTC, blackplayerten commented on easyLanguage/Application/SceneDelegate.swift
> +
- [ ] пустые строки

2023-10-26 12:20 UTC, blackplayerten commented on easyLanguage/Application/SceneDelegate.swift
> +        guard let windowScene = (scene as? UIWindowScene) else { return }
- [ ] скобки у (scene as? ) не нужны

2023-10-26 12:20 UTC, blackplayerten commented on easyLanguage/Auth/ViewController.swift
> +//  ViewController.swift
- [ ] испрвить на название файла

2023-10-26 12:20 UTC, blackplayerten commented on easyLanguage/Auth/ViewController.swift
> +class ViewController: UIViewController {
- [ ] исправить на название класса

2023-10-26 12:20 UTC, blackplayerten commented on easyLanguage/UI/Color/Color/Color.swift
дублирование с файлом выше, какой-то из них удалить или объяснить сакральный смысл этих файлов с одинаковыми названиями
<img width="568" alt="image" src="https://github.com/iOS-vk-education/2023_1_iSnoops/assets/32133991/44d61a5d-834e-474b-a2d5-4d02b429b39a">

2023-10-26 12:20 UTC, blackplayerten commented on easyLanguage/Words/WordsPresentor.swift
> +//  WordsPresentor.swift
- [ ] опечатка – Presenter

2023-10-31 12:04 UTC, gp8stvlv commented on easyLanguage/Application/AppDelegate.swift
> +        // Override point for customization after application launch.
можно это сделать в настройках приложения? 
<img width="984" alt="image" src="https://github.com/iOS-vk-education/2023_1_iSnoops/assets/91904869/beac1604-ef47-42eb-91be-dbf065d5e4ef">

2023-11-06 07:15 UTC, blackplayerten requested changes

2023-11-06 07:15 UTC, blackplayerten commented on README.md
> +  * [Матюшко Матвей](https://github.com/ma14ew) - ответственный за экран распределения задач + делает анимации к экрану
у вас есть экран распределения задач?

2023-11-06 07:15 UTC, blackplayerten commented on easyLanguage/Words/WordsPresenter.swift
> +//  WordsPresentor.swift
здесь тоже presenter

2023-11-12 09:44 UTC, blackplayerten approved these changes

2023-11-12 09:45 UTC, merged