UI grigoriy
iOS-vk-education/2023_1_iSnoops pull request #5
Opened 2023-11-05 20:09 UTC by gp8stvlv

2023-11-05 20:10 UTC, gp8stvlv commented
copmlited calag page

2023-11-06 09:10 UTC, blackplayerten requested changes

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogModel.swift
> +
написать тут что это за экран, в комментариях

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogModel.swift
> +        let defaultImageLink = "https://climate.onep.go.th/wp-content/uploads/2020/01/default-image.jpg"
странно вот так ссылки на картинки зашивать, я думала они в фб будут

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        scrollView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
лучше по функциям разбить, типа setScrollView

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        progressView.translatesAutoresizingMaskIntoConstraints = false
аналогично все остальное по функциям

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        + CGFloat((view.frame.width / 2 - 27 + 19) * CGFloat(categoriesView.countEvenCells()) + 45)
франкенштейн какой-то))) ты хотел сделать квадратную карточку?

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        progressView.setupCountOfWords(with: 120) // должна с бека сумма всех слов приходить
лучше назвать функции setupAllWords(count: Int) и setupWordsInProgress(count: Int)

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +extension TopFiveView: UICollectionViewDataSource {
а ты на всю вью это навешиваешь (с заголовком, подсказкой и тд)? лучше непосредственно внутри на коллекцию

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +        cell.cellConfigure(with: topFiveModel[indexPath.item])
не использовать тут модель с бека. Лучше сделать отдельную для самой вьюшки с уже загруженными картинками

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +        cell.cellConfigure(with: categoriesModel[indexPath.item])
не использовать тут модель с бека. Лучше сделать отдельную для самой вьюшки с уже загруженными картинками

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegate.swift
> +        print("Номер ячейки: \(indexPath.item)")
лучше убирать до ревью такие дебажные вещи

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegateFlowLayout.swift
> +extension TopFiveView: UICollectionViewDelegateFlowLayout {
если это ко всей вью, то как и замечание выше, переписать только к коллекции

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Models/CategoryModel.swift
> +    let ruTitle: String
а если у вас будет 35 языков?) будет 35 тайтлов?)
нет))
лучше тогда сделать поле: language: String = "en", "ru" и тд
и присылать сразу данные на нужном языке

если нужны сразу 2 языка, тогда можно:
1. оставить такую модель, присылать 2 модельки на разных языках и матчить по айди
2. изменить поля, например:
`
struct CategoryModel {
    let categoryId: Int
    let title: [String: String] (где ключ это язык, а значение – его перевод)
...
}
`

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Models/TopFiveWordsModel.swift
> +    let ruTitle: String
аналогично с моделью категорий

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Models/TopFiveWordsModel.swift
> +    let level: String
если в дальнейшем будете развивать приложение и например захотите добавить сортировку по уровню, то string поле будет не удобным в таком случае
было бы легче фильтровать по, например ["A", "1"], ["B", "1"] и тд
просто более универсальная модель получается
переделать или нет это уже как захотите, просто kind recomendation)

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Network/Data/CategoryData.swift
> +    let ruTitle: String
структура на уровень выше очень желательно должна отличаться и названиями тоже (более нативные для пользователя например), например: с бека пришло: topFiveCatetegoryIdByYear: Int -> id: Int

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Network/Data/TopFiveWordsData.swift
> +struct TopFiveWordsData: Decodable {
Data в конце бесполезно, если прям хочется разграничить, то ApiModel например

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Network/Services/CatalogImageManager.swift
> +    func loadImage(from url: URL, completion: @escaping (Result<UIImage, Error>) -> Void) {
перемешаны уровни и ответственности: и загрузка картинки и преобразование ее в ui
лучше тогда отдельно загружать картинку, получать ее в формате data или еще каком-то (приемлемым для uiimage), а на этапе установки ячейки уже писат uiimage(data)

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Network/Services/CatalogImageManager.swift
> +        let mainTreadCompletion: ((Result<UIImage, Error>) -> Void) = { result in
лишние внешние скобки у типа переменной

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Network/Services/CatalogNetworkManager.swift
> +        completion(.success([TopFiveWordsData(topFiveWordsId: 0,
будет удобнее, если на первых порах, пока нет сети, сделать отдельный файлик с мокданными, чтобы удобнее было их менять

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    private let progressLabel = UILabel()
можно в конце не добавлять Label/View

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    override func layoutSubviews() {
а почему не в init?

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +        backgroundLevelView.translatesAutoresizingMaskIntoConstraints = false
разбить на функции по каждому из элементов

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +            textColor = .Catalog.Category.Fonts.customGreen
это градиенты для фона ячеек?

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +        if model.categoryId % 8 == 0 {
так точно быть не должно, нужно придумать что-то более оптимальное (пока не понимаю что это такое)

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +        titleLabel.text = model.ruTitle
в отдельную функцию, например: fill(with: TopFiewCellModel)

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +        }
здесь не должно быть загрузки картинок, должна быть в нетворке

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    func setup() {
это не setup, а setVisualAppearance

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    private let imageManager = CatalogImageManager.shared
убрать

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +                self.titleLabel.text = self.ruTitle
должна по идее быть функция titleLabel.change(to language: String)

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +        }, completion: nil)
можно убрать пустой комплишн

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +    var categoriesModel: [CategoryModel] = [CategoryModel]()
ошибка, view отвечает только за внешний вид, а ты сюда загрузку с сети приплетаешь

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +    private let sortImageView: UIImageView = UIImageView()
лучше тогда addNewCategoryLogo/Icon, sortCategoriesLogo/Icon

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        layout.minimumLineSpacing = 19
лучше рассчитывать исходя из экрана или еще чего-то. кажется, что на маленьких айфонах может быть гигантское расстояние

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        let categoriesCollectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
зачем коллекция внутри коллекции?

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        loadCategories()
убрать

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        }
не понимаю, что оно считает и зачем

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        static let titleText: String = "Категории"
а локализации приложения у вас не будет? было бы весьма логичным

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +    struct Images {
Icons

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
очень большое количество кода с логикой (как будто целый контроллер, а не вью), сделать тогда внешние функции для установки каких-то полей (но не перебарщивать)

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/ProgressView.swift
> +        halfWordsLabel.text = String(count / 2)
почему /2?

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color + configurations.swift
> +            static let customBackground: UIColor = Color(lightMode: prilGrayLightF6F6F6).currentColor
у вас тут только один бекграунд колор, зачем делать custom?
+ будет это выглядеть так: PrimaryColors.Background.customBackground
повторы не несущие смысл
лучше тогда написать grey/yellow или еще что-то, чтобы по названию было понятно в какой именно фон нужно покрасить

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color + configurations.swift
> +            static let customGray: UIColor = Color(lightMode: prilGrayD9D9D9).currentColor
custom убрать. если вы делаете расширение для своих цветов оно уже по умолчанию кастомное

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color + configurations.swift
> +            struct Views {
что за вью? фоны градиентные для них? так и написать: background
а лучше разделить на PinkBackgound { type1, type2 } и так по каждому цвету

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color + configurations.swift
> +            struct Fonts {
очень путает название, шрифты в цветах, а внутри ни одного шрифта
лучше тогда Text

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color + configurations.swift
> +private extension UIColor {
я не поняла зачем этот экстеншн

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color + configurations.swift
> +    struct Default {
бессмысленно, можно сразу написать в опционале ?? .white

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color.swift
так я и не поняла что это за файл

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color/Color.swift
название файлов 0/10

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color/Color.swift
> +/// Структура для управления цветами в различных режимах (светлый, темный, авто).
если у вас сразу будет светлая/темная тема, тогда просьба все цвета сделать под 2 темы

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color/Color.swift
> +        case autoMode
systemMode

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color/Color.swift
> +    init(lightMode: UIColor, darkMode: UIColor? = nil) {
лучше в аргументах mode: Enum

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Color/Color/Color.swift
> +    static var currentModeSystem: ColorSystemModes = .autoMode {
я не поняла что это за переменная: либо тукущая тема или системная (хотя в чем разница)?

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/CustomViewController/CustomViewController.swift
> +class CustomViewController: UIViewController {
0/10 нейминг
какой это экран? если не нужен, то убираем перед реквестом

2023-11-06 09:10 UTC, blackplayerten commented on easyLanguage/UI/Font/Font.swift
> +    case bodyBig
не big а large

2023-11-06 09:17 UTC, gp8stvlv commented on easyLanguage/UI/CustomViewController/CustomViewController.swift
> +class CustomViewController: UIViewController {
кастомный viewController ( прописать заранее background color, мб сделать анимацию загрузки в нем, еще что-то мб) и наследоваться потом от него, чтобы не писать это все в каждом ViewController

2023-11-06 10:52 UTC, gp8stvlv commented on easyLanguage/Catalog/CatalogModel.swift
> +        let defaultImageLink = "https://climate.onep.go.th/wp-content/uploads/2020/01/default-image.jpg"
фб еще не настраивал, думал сразу сделать все модельки в нем
думаю уже после верстки экранов фб делать
а let defaultImageLink = "https://climate.onep.go.th/wp-content/uploads/2020/01/default-image.jpg" просто дефолтная фотка, пока ссылка локально хранится

2023-11-06 10:53 UTC, gp8stvlv commented on easyLanguage/Catalog/CatalogViewController.swift
> +        scrollView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
нужно для каждой вью делать отдельный метод или можно сделать setupConstraints(), где будут все вьюхи?

2023-11-06 10:59 UTC, gp8stvlv commented on easyLanguage/Catalog/Network/Services/CatalogNetworkManager.swift
> +        completion(.success([TopFiveWordsData(topFiveWordsId: 0,
мок данные в сети лежат и там вроде довольно легко менять

2023-11-06 10:59 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +            textColor = .Catalog.Category.Fonts.customGreen
да

2023-11-06 11:00 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +        if model.categoryId % 8 == 0 {
switch case?

2023-11-06 11:02 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        }
это к формуле франкенштейна))

2023-11-06 11:04 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        static let titleText: String = "Категории"
мы успеем все сделать сразу? я думал сначала попробовать все сверстать, прикрутить фб и после уже этим заниматься
ко 2 рк по-хорошему все сверстать и замокать хотя бы

2023-11-06 11:07 UTC, gp8stvlv commented on easyLanguage/UI/Color/Color/Color.swift
> +/// Структура для управления цветами в различных режимах (светлый, темный, авто).
еще не подобрали, жду пока кто-то возьмется за это, не успеваю делать все(

2023-11-06 11:07 UTC, gp8stvlv commented on easyLanguage/UI/Color/Color/Color.swift
> +/// Структура для управления цветами в различных режимах (светлый, темный, авто).
мб когда профиль начнем делать, то и цвета подберем

2023-11-06 11:09 UTC, gp8stvlv commented on easyLanguage/Catalog/CatalogViewController.swift
> +        + CGFloat((view.frame.width / 2 - 27 + 19) * CGFloat(categoriesView.countEvenCells()) + 45)
нет, данная вью требует высоту при инициализации ( иначе просто не будет на экране)
и с помощью нее, на основании конвента внутри вью,  вычисляю высоту

2023-11-06 11:59 UTC, gp8stvlv commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +extension TopFiveView: UICollectionViewDataSource {
не очень понял, лучше сделать внутри TopFiveView сделать папку Delegates и там писать реализацию делегата?

2023-11-06 12:01 UTC, gp8stvlv commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +        cell.cellConfigure(with: topFiveModel[indexPath.item])
а как конфигурировать ячейку? (если что у топ5 (данной коллекции) нет картинок)

2023-11-06 12:03 UTC, gp8stvlv commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +        cell.cellConfigure(with: categoriesModel[indexPath.item])
правильно понял, что тут нужно вынести конфигурацию картинки во внутрь CategoriesView и в ячейке не делать UIImage(data: model.imageLink)... ?
( то есть нужно в CategoriesView создать отдельную модельку с загруженными картинками и ее передавать ячейке)?

2023-11-06 12:05 UTC, gp8stvlv commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegateFlowLayout.swift
> +extension TopFiveView: UICollectionViewDelegateFlowLayout {
про папку с делегатами не очень понял, как вынести extention для коллекции вместо view? 
я же не могу сделать 
extension categoriesCollectionView: UICollectionViewDelegateFlowLayout

2023-11-06 12:12 UTC, gp8stvlv commented on easyLanguage/Catalog/Models/TopFiveWordsModel.swift
> +    let level: String
а можно же будет сделать все равно сортировку по A1 , B2 таким образом
let languageLevels = ["A0", "A1", "B2", "C2", "B1", "A2", "C1"]

let sortedLevels = languageLevels.sorted { (level1, level2) -> Bool in
    // Разбиваем строку на символ и числовую часть
    let char1 = level1.first ?? "A"
    let char2 = level2.first ?? "A"
    
    let num1 = Int(level1.dropFirst()) ?? 0
    let num2 = Int(level2.dropFirst()) ?? 0

    if char1 != char2 {
        return char1 < char2
    } else {
        return num1 < num2
    }
}

2023-11-06 12:17 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    private let progressLabel = UILabel()
можно все не переименовать?)) мне так просто легче ориентироваться, сразу понятно что за тип данных

2023-11-06 12:21 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    override func layoutSubviews() {
он же вроде не сработает повторно при перевороте экрана? я просто читал, что constraints во viewDidLayoutSubviews()  или layoutSubviews() делают
(хотя если вопрос будет ли у нас переворот экрана, то наверное нет)

2023-11-06 12:23 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +        }
отдельный файл в папке network под это создать?

2023-11-06 12:25 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +                self.titleLabel.text = self.ruTitle
(to language: String) этот параметр с бека приходит? (юзер в настройках язык выбирает)?

2023-11-06 12:26 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +    var categoriesModel: [CategoryModel] = [CategoryModel]()
а где делать загрузку данных?

    func loadCategories() {
        model.loadCategory { [weak self] result in
            guard let self = self else {
                return
            }
            switch result {
            case .success(let data):
                self.categoriesModel = data
                DispatchQueue.main.async {
                    self.categoriesCollectionView.reloadData()
                }
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }

2023-11-06 12:28 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        let categoriesCollectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
это же такая инициализация  private lazy var categoriesCollectionView: UICollectionView = { } 
нужен return типа UICollectionView

2023-11-06 12:29 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Views/ProgressView.swift
> +        halfWordsLabel.text = String(count / 2)
убрал, теперь приходит количество изученных слов с бека

2023-11-07 11:13 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogModel.swift
> +        let defaultImageLink = "https://climate.onep.go.th/wp-content/uploads/2020/01/default-image.jpg"
окей, главное не забыть потом ее убрать оттуда

2023-11-07 11:13 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        scrollView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
для каждой вью

2023-11-07 11:15 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        + CGFloat((view.frame.width / 2 - 27 + 19) * CGFloat(categoriesView.countEvenCells()) + 45)
я про странные числа, вроде 27, 19, 18 которые фигурируют в этом вычислении. непонятно откуда они взялись и почему именно такие цифры. ты только на одном айфоне проверял? а если се какой-нибудь запустить)

2023-11-07 11:16 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +extension TopFiveView: UICollectionViewDataSource {
писать около TopFiveCollectionView

2023-11-07 11:17 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +        cell.cellConfigure(with: topFiveModel[indexPath.item])
разделить на разные модели для ui например

2023-11-07 11:18 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +        cell.cellConfigure(with: categoriesModel[indexPath.item])
загрузка картинки в лоадере, ее установка может быть и в такой функции, но главное, чтобы в datasource не присутствовал бек никаким образом

2023-11-07 11:27 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegateFlowLayout.swift
> +extension TopFiveView: UICollectionViewDelegateFlowLayout {
почему не можешь?
`
final class Kek: UICollectionView {}
extension Kek: UICollectionViewDelegateFlowLayout {}
`

2023-11-07 11:28 UTC, blackplayerten commented on easyLanguage/Catalog/Models/TopFiveWordsModel.swift
> +    let level: String
конечно можно, только зачем все так усложнять?

2023-11-07 11:28 UTC, blackplayerten commented on easyLanguage/Catalog/Network/Services/CatalogNetworkManager.swift
> +        completion(.success([TopFiveWordsData(topFiveWordsId: 0,
я вижу что они у тебя конфигурируются в массив здесь

2023-11-07 11:29 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    private let progressLabel = UILabel()
это не критично

2023-11-07 11:29 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +            textColor = .Catalog.Category.Fonts.customGreen
тогда нужно это в отдельные цветовые экстеншены вынести например

2023-11-07 11:30 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +        if model.categoryId % 8 == 0 {
а почему для каждой ячейки нельзя просто рандомный цвет присылать? а не через айди считать под определенное количество слов/категорий

2023-11-07 11:31 UTC, blackplayerten commented on easyLanguage/UI/CustomViewController/CustomViewController.swift
> +class CustomViewController: UIViewController {
что за кастомный? вы хотите сделать базовых класс конроллера, от которого будете наследоваться?

2023-11-07 16:22 UTC, gp8stvlv commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDataSource.swift
> +extension TopFiveView: UICollectionViewDataSource {
внутри папки TopFiveView сделать extension у TopFiveCollectionView?

2023-11-07 17:32 UTC, gp8stvlv commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegateFlowLayout.swift
> +extension TopFiveView: UICollectionViewDelegateFlowLayout {
не очень понимаю с моделькой тогда, как тогда Kek будет знать сколько у него ячеек, какие поля в них

2023-11-07 17:36 UTC, gp8stvlv commented on easyLanguage/Catalog/Models/CategoryModel.swift
> +    let ruTitle: String
это лучше еще и в модельке, которая с бека приходит поменять?

2023-11-07 17:40 UTC, gp8stvlv commented on easyLanguage/Catalog/Network/Data/CategoryData.swift
> +    let ruTitle: String
то есть тут написать лучше просто id или что-то более мудреное типо topFiveCatetegoryIdByYear

2023-11-07 17:45 UTC, gp8stvlv commented on easyLanguage/Catalog/Network/Services/CatalogImageManager.swift
> +    func loadImage(from url: URL, completion: @escaping (Result<UIImage, Error>) -> Void) {
а можно создать отдельную папку Networks -> Manageres и вынести ImageMananager  туда ? (он же будет для всех объектов одинаковый)

2023-11-07 18:06 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        loadCategories()
можно ссылку почитать как правильно работать с моделькой?

2023-11-07 18:42 UTC, gp8stvlv commented on easyLanguage/UI/CustomViewController/CustomViewController.swift
> +class CustomViewController: UIViewController {
цвет, view с загрузкой, view с ошибками ( все при работе с беком)

2023-11-12 10:53 UTC, blackplayerten requested changes

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +    func setup() {
setupTitle или тогда можешь без функции просто во viewDidLoad установить

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        setCategoriesView()
опционально к исправлению: это на самом деле тоже можно вынести как setupUIElements()

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        progressView.setupWordsInProgress(count: 60)
вот это лучше отдельными функциями устанавливать, тк есть часть работы с моделями, а не просто прибивка

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        progressView.topAnchor.constraint(equalTo: scrollView.topAnchor, constant: 18).isActive = true
вот такие константы для прибивок лучше выносить в отдельные структуры, например: 
```
struct UIConstants {
static let top: CGFloat = 18.0
....
}
```

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +        engTitle = model.title["en"]
мне казалось вы ушли от такого решения?

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +        switch model.topFiveWordsId % 3 {
цвета через рандомайзер

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +                self.titleLabel.text = self.ruTitle
можно отдельно настройкой приложения: отметьте предпочитаемый язык для изучения. Если англ значит карточки на русском и флипаются на англ. можно добавить на онбординг + в настройках тоже должна быть возможность смены изучаемого языка

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
> +        static let titleText: String = "Категории"
хорошо

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CollectionViews/CategoriesCollectionView.swift
> +            flowLayout.minimumLineSpacing = UIScreen.main.bounds.width / 20.5
почему именно 20.5? у вас верстка только под 1 айфон?

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/ProgressView.swift
> +    func setupAllWords(count: Int) {
еще бы это в протоколы все обернуть, но уже можно после 2 рк

2023-11-12 10:53 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/TopFiveView.swift
> +    func loadTopFiveWords() {
это кажется должно быть в контроллере

2023-11-12 10:54 UTC, blackplayerten commented
+ подмержить сюда main
+ подмержить потом Catalog_DispatchGroup_Grigoriy

2023-11-17 12:51 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +        engTitle = model.title["en"]
то есть нужно переменные ruTitle и engTitle заменить на native и foreign? 
и также поменять во всех всех файлах (чтобы не было title["ru"] , а было title["native"])?

2023-11-17 13:15 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Views/TopFiveView.swift
> +    func loadTopFiveWords() {
да, еще не делал для топ5 слов
а такой вопрос, откуда у нас все-таки берутся топ5 слов? 
это лучше сделать как 5 рандомных слов юзера (которые у него уже добавлены и не выучены) или как 5 просто рандомных слов приходящих с бека?

2023-11-19 07:20 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +        switch model.topFiveWordsId % 3 {
рандомайзер будет некрасиво( + меняются цвета при каждом входе в приложение (можно тоже на бек конечно отправлять, но не суть, все равно некрасиво получается)
я решил немного логику изменить и сделать цвета не на основании id, а взять номер из indexPath

2023-11-19 10:22 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/Views/CollectionViews/CategoriesCollectionView.swift
> +            flowLayout.minimumLineSpacing = UIScreen.main.bounds.width / 20.5
нет, тестил на iPhone se3 , iPhone 15 , ipnone 15 pro max и на xr
на них вроде не плывет верстка

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +    func setupAllLeanedWords()
learned))))

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +                print(error.localizedDescription)
потом нужно будет сделать обработку ошибок)

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +                print(error.localizedDescription)
потом нужно будет сделать обработку ошибок)

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        topFiveView.heightAnchor.constraint(equalToConstant: UIConstants.TopFiveView.height).isActive = true
а не хочешь динамически считать высоту?

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        let marginHeight = cellHeight * cellCount + categoriesMargin
уже говорила так не считать, нужно будет в дальнейшем обязательно переделать

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +            static let left: CGFloat = 18.0
просто одинаковые константы объединить типа margin/padding

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegate.swift
> +        return inputTopFiveWords?.topFiveWordsCount ?? 0
опционально: можно убрать return, если написание в 1 строку

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    func setupColorsForCategory(with index: Int) {
нужно сделать массив цветов, чтобы по индексу брать уже цвета
потому что сейчас это хардкод

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    func setupColorsForCategory(with index: Int) {
нужно сделать массив цветов, чтобы по индексу брать уже цвета
потому что сейчас это хардкод

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +            backgroundColor = .Catalog.Green.categoryBackground
тогда этот код сократиться до 3-4 строк

2023-11-23 16:11 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +    private var nativeTitle: String?
сложно, как понять какой язык native, а какой иностранный?

2023-11-23 17:54 UTC, gp8stvlv commented on easyLanguage/Catalog/CatalogViewController.swift
> +                print(error.localizedDescription)
как раз под это и хотел использовать CustomViewController)

2023-11-23 17:55 UTC, gp8stvlv commented on easyLanguage/Catalog/Delegates/CatalogCollectionViewDelegate.swift
> +        return inputTopFiveWords?.topFiveWordsCount ?? 0
знаю, думал, так лучше для читаемости

2023-11-28 18:04 UTC, KostyaKulakov commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +            addSubview($0)
https://developer.apple.com/documentation/uikit/uicollectionviewcell/1620133-contentview
https://developer.apple.com/documentation/uikit/uicollectionviewcell

"Don’t directly add subviews to the cell itself."

2023-11-28 19:36 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +            addSubview($0)
ага, уже сказала им)

2023-12-01 20:45 UTC, gp8stvlv commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +    private var nativeTitle: String?
русский - nativeTitle
выбранный в настройках для изучения - foreignTitle
но вообще, по-хорошему, и native язык нужно выбирать выбирать в настройках

2023-12-02 13:37 UTC, blackplayerten approved these changes

2023-12-02 13:37 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +        setTitleLabel()
перенести в инит

2023-12-02 13:37 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/TopFiveCollectionViewCell.swift
> +                self.titleLabel.text = self.nativeTitle
не обязательно везде self писать, нагромождает код)

2023-12-02 13:37 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/Views/CategoriesView.swift
мб в конце если останется время, то перепишите

2023-12-02 13:54 UTC, blackplayerten requested changes

2023-12-02 13:54 UTC, blackplayerten commented on easyLanguage/Catalog/Subviews/CollectionViewCells/CategoryCollectionViewCell.swift
> +    }
объедини в один массив, условно
```swift
static let colors = [
    CellColor(backgroundColor: .Catalog.Green.categoryBackground, textColor: .Catalog.Green.categoryText),
    // ...
]
```

2023-12-02 19:23 UTC, blackplayerten approved these changes

2023-12-02 19:50 UTC, merged