Add new category fix
iOS-vk-education/2023_1_iSnoops pull request #51
Opened 2024-01-03 12:26 UTC by gp8stvlv

2024-02-20 16:21 UTC, blackplayerten requested changes

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/AddNewCategory/AddNewCategoryModel.swift
> +                                                  index: nil)
тут эти параметры можно сделать с инитом значений по умолчанию
тогда инит будет от 1 параметра обязательного для указания: title и еще 10 по умолчанию

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/AddNewCategory/AddNewCategoryModel.swift
>      private let addNewCategoryService = AddNewCategoryService.shared
можно просто service

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/AddNewCategory/AddNewCategoryService.swift
> +    func createNewCategory(with category: CategoryModel, image: UIImage?) async throws -> String?
просто String

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/AddNewCategory/AddNewCategoryService.swift
> +        return uploadCategory["imageLink"] as? String
guard на раскрытие и возвращать ошибку "Не удалось создать категорию"

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
>          model.createNewCategory(with: enteredText, categoryImage: selectedImage) { [weak self] result in
в объявлении аргумента можно просто image

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
> +                self?.delegate?.addNewCategory(with: categoryModel)
guard let self = self else { return error }

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        categoriesViewHeightConstraint = categoriesViewController.view.heightAnchor.constraint(equalToConstant: 50)
опять константы в 50

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +        categoriesViewHeightConstraint = categoriesViewController.view.heightAnchor.constraint(equalToConstant: 50)
и зачем тебе вычисляемый констрейнт

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/Catalog/CatalogViewController.swift
> +            return
ошибка или еще что-то
по идее у пользователя не откроется экран без причины

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
> +    func addNewCategory(with categoryModel: CategoryModel)
почему смена uimodel на model?

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/Network/Models/CategoryModel.swift
> +    var imageLink: String?
почему var

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/Onboarding/OnboardingViewController.swift
> +    let image: UIImage?
почему добавился опционал?

2024-02-20 16:21 UTC, blackplayerten commented on easyLanguage/Onboarding/OnboardingViewController.swift
> +    let image: UIImage?
и почему в мре категории онбординг

2024-03-01 09:45 UTC, gp8stvlv commented on easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
> +    func addNewCategory(with categoryModel: CategoryModel)
она из сети берется, потом добавляется в массив типа CategoryModel на главном экране и они уже отображаются

2024-03-02 10:10 UTC, blackplayerten reviewed
доделать обработку ошибок и заапрувлю

2024-03-02 10:10 UTC, blackplayerten commented on easyLanguage/AddNewCategory/AddNewCategoryViewController.swift
> +                    // TODO: - пробросить ошибку
делаем сразу

2024-03-05 11:26 UTC, blackplayerten approved these changes

2024-03-05 11:27 UTC, merged