added word deletion and reloading count word in category
iOS-vk-education/2023_1_iSnoops pull request #54
Opened 2024-02-16 19:56 UTC by gp8stvlv

2024-02-20 15:34 UTC, blackplayerten requested changes

2024-02-20 15:34 UTC, blackplayerten commented on easyLanguage/Categories/CategoriesViewController.swift
> +                          isDeleted: Bool
плохо делать больше 3 параметров у функции, в таком случае объединяют это в модельку (структуру) и передают

2024-02-20 15:34 UTC, blackplayerten commented on easyLanguage/Categories/CategoriesViewController.swift
> +                          changeTotalCount: Bool,
и можно тогда в таплы объединить, например (changeTotalCount, isDeleted)

2024-02-20 15:34 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailService.swift
> +            comletion(.success(()))
лучше сделать сразу с полноценной логикой

2024-02-20 15:34 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +            })
в отдельную функцию, не читаемо

2024-02-20 15:34 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +            })
и непонятно зачем тут алерт

2024-02-20 15:34 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +        }
можно в 1 строку

2024-02-20 15:34 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +        delegate?.showAlert(with: wordUIModel?.id ?? "")
guard и показ ошибки

2024-03-02 10:54 UTC, blackplayerten requested changes

2024-03-02 10:54 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +                                                                         changeTotalCount: false,
параметры по умолчанию можно сделать

2024-03-02 10:54 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +                print(error.localizedDescription)
так не очень хорошо делать, потому что пользователю порой может вылезти ошибка на подобии
"Error with code iudbfh563"

2024-03-02 10:54 UTC, blackplayerten commented on easyLanguage/Resources/en.lproj/Localizable.strings
> +"detailCancel" = "Cancel";
лучше слова типа cancel обзывать как cancel без привязки к экрану, тк используется на многих экранах (выше есть sortCancel)

2024-03-04 18:11 UTC, gp8stvlv commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +                                                                         changeTotalCount: false,
они каждый раз разные будут, при каждом вызове метода этого (ниже там можно глянуть), есть ли в этом смысл? а так можно структуру сделать и там дефолтные параметры передавать

2024-04-13 09:04 UTC, blackplayerten requested changes

2024-04-13 09:04 UTC, blackplayerten commented on easyLanguage/CategoryDetail/CategoryDetailViewController.swift
> +                                         style: .destructive) { [weak self] _ in
не нужен weak self

2024-04-13 09:04 UTC, blackplayerten commented on easyLanguage/CategoryDetail/Subviews/CategoryDetailCollectionViewCell.swift
> +//            delegate?.showActionSheet(with: wordUIModel?.id ?? "")
убрать

2024-04-27 11:03 UTC, blackplayerten approved these changes

2024-04-27 11:03 UTC, merged