добавлен класс для более удобной работы со строками (для api переводчика можно юзать и при регистрации/авторизации)
iOS-vk-education/2023_1_iSnoops pull request #57
Opened 2024-03-10 16:32 UTC by gp8stvlv

2024-03-18 12:55 UTC, blackplayerten requested changes

2024-03-18 12:55 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordService.swift
> +        guard let url = URL(string: "https://dictionary.yandex.net/api/v1/dicservice.json/lookup?key=dict.1.1.20231020T102336Z.112d6c2d71376dac.b70bd489b5bd6157f8ca6baec7b50467cd0f4593&lang=ru-en&tex
лучше эту строку как константу вынести на строчку выше

2024-03-18 12:55 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordViewController.swift
>          nativeField.placeholder = "Введите слово на русском"
нет локализации

2024-03-18 12:55 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordViewController.swift
очень большой файл получился, надо разбить на несколько файлов

2024-03-18 12:55 UTC, blackplayerten commented on easyLanguage/Catalog/Network/ApiModels/TranslationApiModel.swift
> +}
почему все поля опциональны?

2024-03-18 13:22 UTC, gp8stvlv commented on easyLanguage/AddNewWord/AddNewWordViewController.swift
>          nativeField.placeholder = "Введите слово на русском"
еще доделаю это, там еще UI надо поправить

2024-04-10 21:00 UTC, gp8stvlv commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +}
где лучше сделать переход на главный поток? в presenter?
можно, наверное, еще там создать массив с enevents и весь массив 
dispatchQueue.main.async {
  events.forEach {
  self.view.handle(event: $0)
}
}

2024-04-13 08:54 UTC, blackplayerten requested changes

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordBuilder.swift
> +                      wordUIModel: WordUIModel? = nil
вот это можно в структуру объединить, плохо > 3 параметров передавать обычно

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordBuilder.swift
> +final class AddNewWordBuilder {
protocol

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +}
у тебя презентер отвечает за преобразование данных для vc, чтобы в vc уже готовое все попало

можно вернуться в интеракторе

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +}
еще там создать массив с enevents и весь массив
dispatchQueue.main.async {
events.forEach {
self.view.handle(event: $0)
}
}

вот это я не очень поняла что ты хочешь сделать)

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +    private var wordUIModel: WordUIModel?
эти параметры передаются сразу в функцию
лучше их объединить в структуру

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +    // swiftlint:disable function_body_length
не затыкаем линтер
у тебя получился слишком большой хендлер, разбиваем его

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +                }
в отдельную функцию как минимум

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +            }
аналогично

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +                        DispatchQueue.main.async {
чтобы не писать при каждом возврате, ты можешь это вынести на уровень success

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +                            self?.presenter?.handle(event: .showAlert(message: "Не удалось найти перевод"))
лучше раскрывать и self и presenter

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +                    }
я бы в тернарный оператор определила
```swift
var event: Event // не знаю какой тут тип, наугад написала
isNative ? event = .addForeignTranslate(text: translation) : .addNativeTranslate(text: translation)
presenter.handle(event: event)
```

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +                    self.presenter?.handle(event: .showAlert(message: "Необходимо ввести перевод слова"))
аналогично про тернарный оператор + локализация

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordInteractor.swift
> +        addNewWordService?.apiTranslation(with: word, isNative: isNative, completion: completion)
guard на раскрытие сервиса и возврат ошибки об "нет интернета, не могу перевести"

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordModels.swift
> +    case translateCheckIsOptionText(_ nativeText: String?, _ foreignText: String?)
тут я думаю лучше _ убрать, тк можно запутаться: сначала нейтив передавать или форен

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordModels.swift
> +    case checkIsValidNativeText(text: String?, isNative: Bool) //FIXME: - как правильно возвращать значение?
тут не очень поняла что тебе нужно

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordModels.swift
> +    case addForeignTranslate(text: String)
addTranslate(type: Type, word: String) // type = foreiign or native

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordModels.swift
> +    case updateForeignField(text: String)
по-хорошему тоже объединить

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordService.swift
> +    private var baseUrl = "https://dictionary.yandex.net/api/v1/dicservice.json/lookup?key=dict.1.1.20231020T102336Z.112d6c2d71376dac.b70bd489b5bd6157f8ca6baec7b50467cd0f4593&lang="
let

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordService.swift
> +         path += isNative ? "ru-en" : "en-ru"
можно написать
```swift 
let path = baseURL + (isNative ? "ru-en" : "en-ru")
```

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordService.swift
> +                completion(.success(translationResponse.def?.first?.tr?.first?.text))
лучше раскрыть опционалы и добавить "имена" поосмысленнее, чем def, tr

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordViewController.swift
> +        output?.handle(event: .translateCheckIsOptionText(nativeText, foreignText))
кажется, что отсюда логичнее результат возвращать (пустые поля или нет), чем ниже опять опциолналы раскрывать

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordViewController.swift
> +        }
этого тут быть не должно, я так поняла у тебя это делает outputCheckTranslation

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordViewController.swift
>          self.dismiss(animated: true)
аналогично про проверку

2024-04-13 08:54 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordViewController.swift
> +    func setTranslate() {
можно верстку в отдельный файл-экстеншн вынести, а то логика в целом разрастается и много оч строк у котроллера

2024-04-13 08:58 UTC, blackplayerten requested changes

2024-04-13 08:58 UTC, blackplayerten commented on easyLanguage/AddNewWord/AddNewWordViewController.swift
> +extension AddNewWordViewController: AddNewWordPresenterOutput {
у тебя по clean – 
vc ходит в interator, router (interactor при необходимости в worker) 
interactor возвращает результат в presenter,
presenter передает готовые данные vc
router ходит в другие экраны используя vc

а у тебя тут из vc идет в presenter (судя по AddNewWordPresenterOutput)
это тогда viper

2024-04-30 12:33 UTC, closed without merging