Bugs fix Matvei
iOS-vk-education/2023_1_iSnoops pull request #58
Opened 2024-03-11 15:41 UTC by ma14ew

2024-03-18 12:42 UTC, blackplayerten requested changes

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewController.swift
> +                print("failure learning post")
алерт лучше вывести пользоватнелю

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewController.swift
>                  print(error.localizedDescription)
убрать

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewController.swift
> +        cardsWereSwiped = true
вроде бы в топ 5 добавляются если кол-во свайпов неправильных равно какому-то значению? не увидела этот подсчет. По текущей логике кажется, что любое свайпнутое слово улетает в топ-5

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +        guard let check = try await checkIndividualIdForPostAsync(id: word.id, userId: userId) else { return }
здесь бы тоже throw error

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +                                               userId: String?) async throws -> Bool? {
плохой паттерн возвращать опциональный бул

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +        }
здесь можно через тернарный оператор сразу вернуть значение

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +             try await sortAndDeleteLastAddedWord(with: topFiveWords)
это лучше в отдельную функцию вынести

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +            print("error")
return error

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +        }
это по архитектуре лучше на уровень выше вынести

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +            print(error)
убрать принт

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +            throw error
а тут какого вида ошибка придет пользователю?
не будет какой-нибудь абракадабры вроде "firebase collection words exit with status -5"?

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/TopFiveWordsApiModel.swift
> +    let id: String
лучше сделать тогда ссылку на юзера, типа поле
user: User

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/TopFiveWordsApiModel.swift
> +    let date: Date
не понимаю что это за дата?

2024-03-18 12:42 UTC, blackplayerten commented on easyLanguage/Statistics/StatisticsView.swift
вынеси файл со статистикой в отдельный мр пожалуйста

2024-03-18 12:46 UTC, ma14ew commented on easyLanguage/Network/ApiModels/TopFiveWordsApiModel.swift
> +    let id: String
Вот этот момент немного не понял)

2024-03-18 12:47 UTC, ma14ew commented on easyLanguage/Network/ApiModels/TopFiveWordsApiModel.swift
> +    let date: Date
Дата добавления слова в топ-5, с помощью нее мы убираем самое старое слово, если их становится больше 5

2024-03-18 12:47 UTC, ma14ew commented on easyLanguage/Statistics/StatisticsView.swift
Ок!

2024-03-18 12:48 UTC, ma14ew commented on easyLanguage/LearningView/LearningViewController.swift
>                  print(error.localizedDescription)
А почему?

2024-03-18 12:48 UTC, ma14ew commented on easyLanguage/LearningView/LearningViewController.swift
> +        cardsWereSwiped = true
Вроде как и обговаривали так, уточню

2024-03-18 12:50 UTC, ma14ew commented on easyLanguage/LearningView/LearningViewService.swift
> +                                               userId: String?) async throws -> Bool? {
Хорошо

2024-03-18 12:50 UTC, ma14ew commented on easyLanguage/LearningView/LearningViewService.swift
> +        }
Хорошо

2024-03-18 12:50 UTC, ma14ew commented on easyLanguage/LearningView/LearningViewService.swift
> +             try await sortAndDeleteLastAddedWord(with: topFiveWords)
ок

2024-03-18 12:51 UTC, ma14ew commented on easyLanguage/LearningView/LearningViewService.swift
> +        }
Вот тут не понял, что нужно сделать?

2024-03-18 13:04 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewController.swift
>                  print(error.localizedDescription)
не очень оставлять принты в приложении

2024-03-18 13:06 UTC, blackplayerten commented on easyLanguage/LearningView/LearningViewService.swift
> +        }
вот эти 3 строки вынести туда, откуда у тебя идет вызов этой функции.
Почему плохо оставлять здесь: ты в аргументы функции передаешь модель и внутри тела ее преобразовываешь. Лучше все преобразования необходимые делать до, а в функцию уже слать подготовленные данные

2024-03-18 13:17 UTC, blackplayerten requested changes

2024-03-18 13:17 UTC, blackplayerten commented on easyLanguage/Network/ApiModels/TopFiveWordsApiModel.swift
> +    let date: Date
лучше добавить коммент на это

2024-04-04 09:54 UTC, ma14ew commented on easyLanguage/LearningView/LearningViewController.swift
> +        cardsWereSwiped = true
Уточнял,  вот так у нас :  По текущей логике кажется, что любое свайпнутое слово улетает в топ-5

2024-04-08 18:05 UTC, blackplayerten approved these changes

2024-04-08 18:05 UTC, blackplayerten commented on easyLanguage.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = U5P97KCFM7;
наверное лучше оставить как было)

2024-04-09 14:21 UTC, ma14ew commented on easyLanguage.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = U5P97KCFM7;
Поправил)

2024-04-09 14:52 UTC, blackplayerten approved these changes

2024-04-09 14:52 UTC, merged