фикс
iOS-vk-education/2023_1_iSnoops pull request #70
Opened 2024-05-04 10:52 UTC by gp8stvlv

2024-05-04 12:47 UTC, blackplayerten requested changes

2024-05-04 12:47 UTC, blackplayerten commented on easyLanguage/Wrappers/Trimmed.swift
> +            value = filteredString
```swift
return newValue.split(separator: " ").joined(separator: " ")
```

2024-05-06 20:08 UTC, Huseyn420 requested changes

2024-05-06 20:08 UTC, agscpp commented on easyLanguage/Wrappers/Trimmed.swift
> +                .lowercased()
Зачем два lowercased?

2024-05-06 20:08 UTC, agscpp commented on easyLanguage/Wrappers/Trimmed.swift
> +                .joined(separator: " ")
Зачем разбивать по пробелу, а потом сразу же соединять?)

2024-05-06 20:08 UTC, Huseyn420 commented on easyLanguage/CategoryDetail/CategoryDetailService.swift
>                  print(error)
А здесь форматеру нормально? Разве не должно получиться что-то похожее на:
```
func reloadIsLearned(with id: String, isLearned: Bool, swipesCounter: Int) {
  dataBase.collection("words").document(id).updateData([
    "isLearned": isLearned,
    "swipesCounter": swipesCounter,
  ]) { error in
    if let error = error {
      print(error)
    }
  }
}
```

2024-05-07 17:26 UTC, Huseyn420 approved these changes

2024-05-07 17:32 UTC, merged