Feature/delete category
iOS-vk-education/2023_1_iSnoops pull request #72
Opened 2024-05-04 13:31 UTC by gp8stvlv

2024-05-04 14:26 UTC, blackplayerten requested changes

2024-05-04 14:26 UTC, blackplayerten commented on easyLanguage/Categories/CategoryService.swift
> +                        completion(.success(true))
ты здесь возвращаешь ошибку или бул
как правило у вас в приле нет конвертации фб ошибок в собсвенные
из этого можно предположить, что тебе тут возвращать error не нужно, тк в дальнейшем он не будет испрользоваться напрямую
то есть можно спокойно написать
```swift
if let error = error {
    completion(false)
} else {
    completion(true)
}
```

2024-05-04 14:26 UTC, blackplayerten commented on easyLanguage/Categories/Subviews/CategoryCollectionViewCell.swift
> +
dry
лучше тогда объединить с прессом по удалению слов

2024-05-04 14:26 UTC, blackplayerten commented on easyLanguage/Categories/Subviews/CategoryCollectionViewCell.swift
> +        delegate?.showActionSheet(with: model.linkedWordsId)
раз ты тут используешь только id имеет смысл в селф заинитить только id, а не всю структуру

2024-05-04 14:26 UTC, blackplayerten commented on easyLanguage/Wrappers/Trimmed.swift
> +            value = filteredString
про это в предыдущем мре писала

2024-05-15 10:28 UTC, Huseyn420 commented on easyLanguage/Categories/CategoriesViewController.swift
> +        collectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
Лучше всего делать так, чтобы не забыть, например, об active в одном из констреинтов.
```
NSLayoutConstraint.activate([
   collectionView.topAnchor.constraint(equalTo: addNewCategoryLogo.bottomAnchor,
                                               constant: 10),
   collectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant:
                                               UIConstants.CategoriesCollectionView.horizontally)
  ...
])
```

2024-05-15 10:29 UTC, Huseyn420 commented on easyLanguage/Categories/CategoriesViewController.swift
> +        let alertController = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
А что это за алерт без title и message?

2024-05-15 11:52 UTC, gp8stvlv commented on easyLanguage/Categories/CategoriesViewController.swift
> +        collectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
такая верстка на всех экранах, кол стайл не будет ломать?)
по-хорошему, везде переписать

2024-05-15 11:53 UTC, Huseyn420 commented on easyLanguage/Categories/CategoriesViewController.swift
> +        collectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
Но окей, пока оставим)

2024-05-15 19:46 UTC, Huseyn420 commented on easyLanguage/Categories/CategoriesViewController.swift
> +        let alertController = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
Обсудили в ЛС. Все нормально

2024-05-15 19:46 UTC, Huseyn420 approved these changes

2024-05-15 19:46 UTC, merged