add StatisticView
iOS-vk-education/2023_1_iSnoops pull request #75
Opened 2024-05-07 10:57 UTC by ma14ew

2024-05-07 11:32 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +    let radius: CGFloat = 243
Лучше все константы выносить подобным образом
```
struct MainPieBar: View {
     private enum Constants {
         static let lineWidth: CGFloat = 15
         ...
     }
     ...
```

2024-05-07 11:32 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +                ForEach(data[index].indices, id: \.self) { index1 in
Лучше не называть переменные в виде переменная1, переменная2, переменная3) Добавть чуть больше контекста к названию словами

2024-05-07 11:32 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +                ForEach(data[index].indices, id: \.self) { index1 in
Может indexDelta назвать (на основании строки 35)?

2024-05-07 11:32 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +                }
А форматер кода здесь запускался?)

2024-05-07 11:32 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +                       height: radius - (computeLevel(data.count) * 2))
Может расчет вынести в отдельную функцию?

2024-05-07 11:32 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +        return (lineWidth+lineSpace) * CGFloat(level)
Пробел до и после "+")

2024-05-07 12:04 UTC, agscpp commented on easyLanguage/Statistic/Charts/PieBar.swift
> +                sum = data[index].value + sum - delta
```
                for point in 0...index {
                    sum += data[point].value
                }
                sum -= delta
```

2024-05-07 12:04 UTC, agscpp commented on easyLanguage/Statistic/Charts/PieBar.swift
> +                sum = data[index].value + sum - delta
Или что-то на подобии этого:
```
sum = data.prefix(index).reduce(0, { $0.value + $1.value }) - delta
```

PS возможно, по синтаксису написал не верно, но смысл думаю понятен)

2024-05-07 12:04 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +            }
У тебя и так sum = 0 изначально, так что переопределение излишнее. Можно написать так:
```
if data[index].value != 1 {
     sum = delta
}

2024-05-07 16:22 UTC, Huseyn420 requested changes

2024-05-07 16:22 UTC, agscpp commented on easyLanguage/Statistic/Charts/PieBar.swift
> +                sum += delta
По аналогии с кодом, который я выше написал можно сделать. Единственное, prefix можно заменить на filter

2024-05-07 16:22 UTC, agscpp commented on easyLanguage/Statistic/Charts/PieBar.swift
> +        let delta =  (((asin(lineWidth * 0.5 / ((calcWidth - lineWidth) * 0.5))) * (180 / .pi)) / 360) // 0.0083
Два пробела после равно) Нужно поправить

Точно ли нельзя сократить количество скобок? По-моему, самые крайние скобки не нужны)

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +        let delta =  (((asin(lineWidth * 0.5 / ((calcWidth - lineWidth) * 0.5))) * (180 / .pi)) / 360) // 0.0083
скобки вокруг asin тоже лишние)

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +        var returnData: [[PieBarValues]] = data
[[PieBarValues]] излишнее
Здесь и так понятен тип по data

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +            for pie in 0..<returnData[levelIndex].count
Фигурные скобки обязательно нужно писать и отступ делать для кода в этом блоке

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/PieBar.swift
> +            .animation(.linear(duration: 0.5),
Константы лучше выносит по аналогии с кодом, который я выше писал

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/WeekStatisticChart.swift
> +                                y: .value("Количество слов", lineData.countAdded)
Тоже вынести в Localizable.strings?

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/WeekStatisticChart.swift
> +                        Text("Пусто!")
Вынести в Localizable.strings

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/Charts/WeekStatisticChart.swift
> +            }.frame(height: 300)
Константу лучше вынести)

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/StatisticModel.swift
> +import Charts
Вроде, лишний импорт

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/StatisticService.swift
> +            }
А в do catch точно есть необходимость?)

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/StatisticService.swift
> +                .whereField("profileId", isEqualTo: uid)
Я бы в константы вынес "categories", "profileId" и тд

2024-05-07 16:22 UTC, Huseyn420 commented on easyLanguage/Statistic/StatisticService.swift
> +        }
Можно else и не писать

2024-05-07 17:40 UTC, gp8stvlv approved these changes

2024-05-07 17:40 UTC, gp8stvlv commented on easyLanguage/TabBar/TabBarController.swift
> +//    private var swiftUIVC: UIViewController {
вопрос, а это для теста экрана нужен?

2024-05-10 14:13 UTC, ma14ew commented on easyLanguage/TabBar/TabBarController.swift
> +//    private var swiftUIVC: UIViewController {
Да)

2024-05-13 08:44 UTC, ma14ew commented on easyLanguage/Statistic/Charts/PieBar.swift
> +                }
Ни на что не ругается)

2024-05-13 13:25 UTC, Huseyn420 approved these changes

2024-05-13 13:34 UTC, merged