Захардкоженный экран ачивок + база для экрана ачивок/статистики
iOS-vk-education/2023_1_iSnoops pull request #79
Opened 2024-05-12 14:12 UTC by Senyakas

2024-05-12 16:14 UTC, Huseyn420 requested changes

2024-05-12 16:14 UTC, agscpp commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +                .frame(height: 0)
Зачем высота 0?

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +                Text(profile?.name ?? "Имя").bold()
Нужно "Имя" вынести в Localizable.strings и написать переводы на все поддерживаемые языки)

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +                    Button("Достижения") {
Достижение тоже нужно вынести в Localizable.strings)

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +                    Button("Статистика") {
Тоже выносим в Localizable.strings)

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +                    .font(.title2)
Формотирование, вроде, неверное) Лучше запустить форматер на изменения)
```
Text(profile?.name ?? "Имя")
    .bold()
    .font(.title2)
```

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +                .padding(.bottom, 10)
Лучше подобные константы выносит в отдельные переменные)
```
struct AchievementStaticsBaseViewController: View {
     private enum Constants {
         static let variableName : CGFloat = 5
         ...
     }
     ...
```

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +    @State private var achievementToggle = true
https://dzen.ru/a/XygFgBmi5ivLFvfL

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +                .background(SwiftUI.Color(UIColor.PrimaryColors.Background.background))
Как будто съехало)

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +        .navigationTitle("Достижения")
Тоже нужно вынести в Localizable.strings

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementViewController.swift
> +    @State private var achievementButtonColor = SwiftUI.Color.blue
В вашем проекте есть файл с цветами. Лучше вынести его туда)

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementViewController.swift
> +                HStack (spacing: 15) {
Константы из этого файла тоже лучше вынести таким образом:
```
struct AchievementStaticsBaseViewController: View {
     private enum Constants {
         static let variableName : CGFloat = 5
         ...
     }
     ...
```

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementViewController.swift
> +        .listStyle(.plain)
Формотирование поехало

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/Profile/ProfileViewController.swift
> +        achievementsImageView.image = UIImage(systemName: "chart.bar")
Лучше тоже в константу вынести

2024-05-12 16:14 UTC, Huseyn420 commented on easyLanguage/UI/Color/Color + configurations.swift
> +import SwiftUI
А зачем импорт добавился, если код не изменился?

2024-05-12 16:24 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +    @State private var isUIKitScreenPresented = false
А как переменная используется?

2024-05-13 11:22 UTC, Senyakas commented on easyLanguage/Profile/ProfileViewController.swift
> +        achievementsImageView.image = UIImage(systemName: "chart.bar")
договорились не выносить)

2024-05-13 11:28 UTC, Senyakas commented on easyLanguage/Achievements/AchievementStaticsBaseViewController.swift
> +    @State private var achievementToggle = true
я попытался

2024-05-13 11:57 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementViewController.swift
> +    }
Такое штуки лучше в начале класса писать

2024-05-13 11:59 UTC, Huseyn420 approved these changes

2024-05-13 12:00 UTC, Huseyn420 commented on easyLanguage/Achievements/AchievementViewController.swift
> +    }
Подвинем вверх и вольем изменения

2024-05-13 12:23 UTC, agscpp approved these changes

2024-05-13 12:23 UTC, merged