Profile chistyakov
iOS-vk-education/2023_1_iSnoops pull request #8
Opened 2023-12-02 09:22 UTC by Senyakas

ура

2023-12-02 14:25 UTC, blackplayerten requested changes
нужен созвон,невозможно так построчно описать все ошибки

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +final class ProfileViewController: UIViewController, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UITextFieldDelegate{
комментарий от Кости Кулакова: UITextFieldDelegate {
+ мой комментарий:
лучше делегаты по экстеншенам разбить с подписями типа MARK – улучшает читабельность

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Resources/Assets.xcassets/ProfileEmptyImage.imageset/Contents.json
> +      "filename" : "image 80.png",
комментарий от Кости Кулакова: 1x не нужно добавлять, тк таких устройств уже нет

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +//protocol ProgressSetup {
если ненужно – убираем

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +    private let line = UIView()
не line, а divider скорее всего

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +    private let scrollView = UIScrollView()
необходимо разбить это все на отдельные классы, типа progress view:
```swift
initialsView: UIView {

let firstNameTF = UITextField()
let lastNameTF = UITextField()
...

```

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +    let automaticThemeLabel = UILabel()
это тоже можно вынести в отдельный компонент с темой

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        view.backgroundColor = .white
у вас кажется есть CustomViewController, в котором уже настраивается фон + обработка ошибок с бека + еще что-то
тогда ProfileViewController: CustomViewController

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        lastNameLabel.text = "Чистяков"
если ты это имел в виду как подсказку, то есть у текстфилдов поле placeholder

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        [firstNameBackgroundView, lastNameBackgroundView, firstNameLabel, lastNameLabel, progressView, labelUnderTextField, lightThemeButton, automaticThemeButton, darkThemeButton, lightThemeLabel, a
<img width="939" alt="image" src="https://github.com/iOS-vk-education/2023_1_iSnoops/assets/32133991/0d1acc42-5598-4b34-abe7-e0c08991a1ba">
нужно поправить, проект не собирается

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        [firstNameBackgroundView, lastNameBackgroundView, firstNameLabel, lastNameLabel, progressView, labelUnderTextField, lightThemeButton, automaticThemeButton, darkThemeButton, lightThemeLabel, a
ошибки линтера тоже править

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        super.viewDidLayoutSubviews()
тут мы код не пишем

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        firstNameBackgroundView.heightAnchor.constraint(equalToConstant: 35).isActive = true
каждая отдельная вью должна прибиваться в своей функции

2023-12-02 14:25 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +    func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
работу с картмнкой тоже можно к отдельному view-компоненту вынести

2023-12-02 14:38 UTC, blackplayerten requested changes

2023-12-02 14:38 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +    func textFieldDidEndEditing(_ textField: UITextField) {
пометка для себя: зачем делегаты для тф

2023-12-02 16:41 UTC, gp8stvlv commented on easyLanguage/Profile/ProfileViewController.swift
> +        view.backgroundColor = .white
еще нет этого, но будет)

2023-12-02 17:33 UTC, gp8stvlv commented on easyLanguage/Profile/ProfileViewController.swift
> +    func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
такое есть в папке UI

2023-12-13 11:07 UTC, blackplayerten requested changes

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        setProgressView()
лучше перенести во viewDidLoad

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +    func setAppearance() {
setTipAppearance()

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        progressView.setupAllWords(count: 120)
это в отдельную функцию

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        static let text: String = "Укажите имя и, если хотите, добавьте фотографию для Вашего профиля"
это можно просто текстом оставить, обычно в константы цифры выносят

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        static let allWords: CGFloat = 60
убрать

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        static let marginRight: CGFloat = -20
можно объединить в 1 переменную

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    private let automaticThemeButton = UIButton()
system

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    private let lightThemeButton = UIButton()
lightButton
слово theme в названиях излишне

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    private let themeLabel = UILabel()
title

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    private let darkThemeLabel = UILabel()
отделить enter'ами кнопки и подписи

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    override func layoutSubviews() {
аналогично перенести в инит

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +        return ThemeLabel.marginTop + ThemeLabel.height + Button.marginTop
в функциях где телом является одна строка слово return можно не писать

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +        configureCircularButton(lightThemeButton, color: .blue, isActive: true)
нейминг можно улучшить: configure(button: UIButton)

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +        configureLabel(darkThemeLabel, withText: "Темная")
аналогично configure(label: UILabel, with text: String)

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    func configureCircularButton(_ button: UIButton, color: UIColor, isActive: Bool) {
+ добавить марки, экстеншены для наглядности

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +            print("Выбрана светлая тема")
убрать :)

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/UserInformationView.swift
> +        static let imageSize: CGFloat = 130
проверял на каком-нибудь iphoneSE как такой размер картинки будет смотреться?

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/TabBar/TabBarController.swift
> +        profileViewController.tabBarItem = UITabBarItem(title: title, image: image, tag: 0)
tag 1 или 2

2023-12-13 11:07 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    @objc func themeButtonTapped(_ sender: UIButton) {
нужно будет переписать под будущую логику с выбором темы, например так: 
```swift 
@objc func themeButtonTapped(_ sender: UIButton) {
    var buttons = [lightThemeButton, automaticThemeButton, darkThemeButton]
    guard let currentStateButton = buttons.first(where: { $0.isSelected }) else { return }
    guard let newStateButton = buttons.first(where: { $0 == sender }) else { return }
    switchButtonState(button: currentStateButton, active: false)
    switchButtonState(button: newStateButton, active: true)
}

func switchButtonState(button: UIButton, active: Bool) {
    let color: UIColor = active ? .blue : .white
    button.isSelected = active
    button.backgroundColor = color
}
```

Помимо этого массив buttons объявленный тут нужно вынести как переменную класса и сделать как:
```swift 
var buttons = Array(repeating: UIButton(), count: 3)
```
После этого:
- сделать по аналогии с лейблами для подписи
- поменять верстку и визуальные составляющие кнопок исходя из массива
- верстка кнопки будет удобнее, если в одной функции наверстать сразу кнопку + текст к ней

И стейт тоже внести, я просто для примера сделала его Int, по факту у вас дальше будет из модели делаться или из енама темы...
```swift 
var state = 0
```

2023-12-13 11:10 UTC, blackplayerten commented
сделать марки и экстеншены уже, например: 
// MARK: - set appearance elements
// MARK: - set constraints

2023-12-17 15:17 UTC, blackplayerten requested changes

2023-12-17 15:17 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        static let height: CGFloat = 30
выносить следует только те константы, которые повторяются в нескольких элементах или в пределах одного элемента

2023-12-17 15:17 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    var labelText = ["Светлая", "Автоматически", "Темная"]
неправильно, у тебя ошибка логическая: у тебя нет привязки количества тем к кнопкам

надо вынести в отдельное view, где будет сделана кнопка + текст
и сделать еще привязку к теме опеределенной

2023-12-17 15:17 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    var labelText = ["Светлая", "Автоматически", "Темная"]
```swift
enum Theme: CaseIterable { /// такой у вас в проекте уже есть, надо его доработать
    case light
    case dark
    case system

    func description() -> String {
        switch self {
        case .light:
            "Светлая"
        case .dark:
            "Темная"
        case .system:
            "Системная"
        }
    }
}

class ChoosingThemeView {
    var components: [(UIButton, UILabel)]
    init() {
        components = Theme.allCases.map {
            let label = UILabel()
            label.text = $0.description()
            return (UIButton(), label)
        }
    }
}
```

2023-12-17 15:17 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    struct ThemeTitle {
константы убрать

2023-12-17 15:17 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/ChoosingThemeView.swift
> +    }
неправильная функция
ты делаешь в одной функции две вещи: переключаешь кнопку и делаешь смену темы
так не должно быть
про переключение кнопки был уже коммент выше
нужно добавить отдельно функцию на переключение темы
p.s. индексов в аргументах быть не должно

2023-12-17 15:17 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/UserInformationView.swift
> +        static let text: String = "Чистяков"
не выносим тексты и картинки в константы

2023-12-17 15:19 UTC, blackplayerten commented
1. расположить все переменные и функции в том порядке, на котором они находятся на экране
2. функции с констреинтами можно ставить в самый конец, тк их большой код затмевает логику экрана
3. сделать private все, что используется локально

2023-12-27 12:18 UTC, blackplayerten requested changes

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +    private let getOutButton = UIButton()
logout

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        setWordsInProgressLabel()
вынеси это в одну функцию в экстеншн)

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +                    self?.didSelectImage(image)
линтер не ругается на отступы?

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        userInformationView.setImage(image: image)
а почему это не вызвать в 57 строке?

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        progressView.setupAllLearnedWords(count: 120)
спроси у Гриши, как прокинуть сюда актуальные данные с фаербейза

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Profile/ProfileViewController.swift
> +        }
не вижу действия для разлогина

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/UserInformationView.swift
> +    // Первые две функции пока не работают
убрать, если не работает

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Profile/Subviews/UserInformationView.swift
> +        firstNameTextField.text = "Арсений"
должны быть данные пользователя

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Resources/Assets.xcassets/Onboarding_2.imageset/Снимок экрана 2023-12-27 в 04.08.00 1.png
заполнить слова, не 0/0, а 15/120, 5/55, 0/78

2023-12-27 12:18 UTC, blackplayerten commented on easyLanguage/Resources/Assets.xcassets/Onboarding_3.imageset/Onboarding_3.png
у знаю не знаю должен быть счетчик

2023-12-27 14:34 UTC, Senyakas commented on easyLanguage/Profile/ProfileViewController.swift
> +                    self?.didSelectImage(image)
нет)

2023-12-28 14:53 UTC, blackplayerten approved these changes

2023-12-28 14:53 UTC, merged