добавлена coredata для экрана категорий + добавле категории + удаление
iOS-vk-education/2023_1_iSnoops pull request #94
Opened 2024-05-17 22:29 UTC by gp8stvlv

2024-05-17 22:32 UTC, gp8stvlv commented on easyLanguage/AddNewCategory/AddNewCategoryModel.swift
> +//                let imageLink = try await service.createNewCategory(with: categoryModel, image: image)
это нужно, если не кор дату использовать, нужно будет настроить синхронизацию, пока так решил оставить

2024-05-17 22:46 UTC, gp8stvlv commented on easyLanguage/Components/AddWord/Interactor/AddWordService.swift
> +}
не очень понимаю откуда этот файл в ПР, если он уже есть в проекте в таком же виде)

2024-05-17 22:46 UTC, gp8stvlv commented on easyLanguage/Components/Auth/Views/RegistrationViewController.swift
> +//
и этот тоже)

2024-05-18 11:43 UTC, Huseyn420 requested changes

2024-05-18 11:43 UTC, Huseyn420 commented on easyLanguage/AddNewCategory/AddNewCategoryModel.swift
> +    static let defaultImage = UIImage(systemName: "questionmark")!
Не очень хорошо использовать !, но поскольку это изображение по умолчанию, то пока оставим всё как есть.

2024-05-18 11:43 UTC, Huseyn420 commented on easyLanguage/Categories/CategoriesModel.swift
> +            let counts = loadCDWordsCounts(with: category.linkedWordsId ?? "")
Можно написать следующим образом:
let (totalWordsCount, studiedWordsCount) = loadCDWordsCounts(with: category.linkedWordsId ?? "")

Позволит избежать counts.1, counts.0

2024-05-18 11:43 UTC, Huseyn420 commented on easyLanguage/CoreData/CoreDataService.swift
> +                                               in: persistentContainer.viewContext)!,
Давай без !

guard в else у которого мы будем завершать без сохранения и записывать в лог

2024-05-18 11:53 UTC, Huseyn420 approved these changes

2024-05-18 11:53 UTC, merged